name: Build & Release

on:
  push:
    tags:
      - 'v*'  # Run only when a new version tag is pushed

jobs:
  build-macos:
    runs-on: macos-14
    strategy:
      matrix:
        arch: [arm64, x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build macOS binary
        run: |
          pyinstaller --onefile --name Spread_Pattern_Analysis --distpath dist main.py
          mv dist/Spread_Pattern_Analysis.dmg Spread_Pattern_Analysis-${{ github.ref_name }}-macx-${{ matrix.arch }}-Release.dmg

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-${{ matrix.arch }}
          path: Spread_Pattern_Analysis-*-macx-${{ matrix.arch }}-Release.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Build Windows executable
        run: |
          pyinstaller --onefile --name Spread_Pattern_Analysis --distpath dist main.py
          mv dist/Spread_Pattern_Analysis.exe Spread_Pattern_Analysis-${{ github.ref_name }}-win64-Release.exe

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: Spread_Pattern_Analysis-*-win64-Release.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y p7zip-full
          pip install -r requirements.txt pyinstaller

      - name: Build Linux AppImage
        run: |
          pyinstaller --onefile --name Spread_Pattern_Analysis --distpath dist main.py
          mv dist/Spread_Pattern_Analysis Spread_Pattern_Analysis-${{ github.ref_name }}-x86_64-Release.AppImage

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: Spread_Pattern_Analysis-*-x86_64-Release.AppImage

  create-release:
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Source Code
        run: |
          git archive --format=zip --output=Spread_Pattern_Analysis-${{ github.ref_name }}-source.zip HEAD
          git archive --format=tar.gz --output=Spread_Pattern_Analysis-${{ github.ref_name }}-source.tar.gz HEAD

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/macOS-arm64/*
            artifacts/macOS-x86_64/*
            artifacts/Windows/*
            artifacts/Linux/*
            Spread_Pattern_Analysis-${{ github.ref_name }}-source.zip
            Spread_Pattern_Analysis-${{ github.ref_name }}-source.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
