name: Release Builds

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]  # macos-12 is x86_64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          # Fix numpy/OpenCV issues
          pip install --force-reinstall numpy opencv-python-headless

      - name: Build executable
        shell: bash
        run: |
          pyinstaller --onefile --name=rifle_spread_analysis main.py
          mkdir -p release
          
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/rifle_spread_analysis.exe release/rifle_spread_analysis-windows-x86_64.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            # On x86_64 runner, we get native x86_64 build
            mv dist/rifle_spread_analysis release/rifle_spread_analysis-macos-x86_64
            
            # Now build ARM64 version using cross-compilation
            echo "Building ARM64 version..."
            pip install --force-reinstall --no-binary :all: pillow
            export PYTHON_CONFIGURE_OPTS="--enable-universalsdk --with-universal-archs=arm64"
            python -m PyInstaller --onefile --name=rifle_spread_analysis_arm main.py
            mv dist/rifle_spread_analysis_arm release/rifle_spread_analysis-macos-arm64
          else  # Linux
            mv dist/rifle_spread_analysis release/rifle_spread_analysis-linux-x86_64
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine artifacts
        run: |
          mkdir -p combined-release
          find artifacts -name "rifle_spread_analysis*" -exec cp {} combined-release/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: combined-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
