name: Release Builds

on:
  push:
    tags:
      - "v*"  # Triggers on tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        shell: bash
        run: |
          pyinstaller --onefile --name=rifle_spread_analysis main.py
          mkdir -p release
          
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/rifle_spread_analysis.exe release/rifle_spread_analysis-windows-x86_64.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            # Native ARM64 build
            mv dist/rifle_spread_analysis release/rifle_spread_analysis-macos-arm64
            
            # Build x86_64 binary using Rosetta 2
            echo "Building x86_64 version..."
            arch -x86_64 python -m PyInstaller --onefile --name=rifle_spread_analysis_x86 main.py
            mv dist/rifle_spread_analysis_x86 release/rifle_spread_analysis-macos-x86_64
          else  # Linux
            mv dist/rifle_spread_analysis release/rifle_spread_analysis-linux-x86_64
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine artifacts
        run: |
          mkdir -p combined-release
          find artifacts -name "rifle_spread_analysis*" -exec cp {} combined-release/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: combined-release/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
