name: Create Release Assets

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            artifact: macx-arm64-Release.dmg
            build_script: build-mac-arm64.sh
          - os: macos-latest
            artifact: macx-x86_64-Release.dmg
            build_script: build-mac-x86.sh
          - os: windows-latest
            artifact: win64-Release.exe
            build_script: build-windows.ps1
          - os: ubuntu-latest
            artifact: x86_64-Release.AppImage
            build_script: build-linux.sh

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up build environment
        run: |
          echo "Setting up build environment..."
          # Add your environment setup commands here
          # For example:
          # brew install packages (on macOS)
          # sudo apt-get install packages (on Ubuntu)
          # choco install packages (on Windows)
      
      - name: Make build script executable (Linux/Mac)
        if: runner.os != 'Windows'
        run: chmod +x ${{ matrix.build_script }}
      
      - name: Build artifact
        run: |
          echo "Running build script..."
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell ./${{ matrix.build_script }}
          else
            ./${{ matrix.build_script }}
          fi
          
      - name: Rename artifact
        run: |
          mv built-artifact Spread_Pattern_Analysis-v${{ github.ref_name }}-${{ matrix.artifact }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Spread_Pattern_Analysis-v${{ github.ref_name }}-${{ matrix.artifact }}
          path: Spread_Pattern_Analysis-v${{ github.ref_name }}-${{ matrix.artifact }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ github.ref_name }}
          body: Automated release with multi-platform binaries
          files: |
            artifacts/Spread_Pattern_Analysis-v${{ github.ref_name }}-*.dmg
            artifacts/Spread_Pattern_Analysis-v${{ github.ref_name }}-*.exe
            artifacts/Spread_Pattern_Analysis-v${{ github.ref_name }}-*.AppImage
