name: Release Builds

on:
  push:
    tags:
      - "v*"  # Triggers on tags like v1.0.0

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build executable
        shell: bash  # Force Bash on Windows (or use `pwsh` for PowerShell)
        run: |
          pyinstaller --onefile --name=rifle_spread_analysis main.py
          mkdir -p release
          
          # Rename based on OS
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/rifle_spread_analysis.exe release/rifle_spread_analysis-windows-x86_64.exe
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            # Check if it's ARM64 or x86_64
            if [[ "$(uname -m)" == "arm64" ]]; then
              mv dist/rifle_spread_analysis release/rifle_spread_analysis-macos-arm64
            else
              mv dist/rifle_spread_analysis release/rifle_spread_analysis-macos-x86_64
            fi
          else  # Linux
            mv dist/rifle_spread_analysis release/rifle_spread_analysis-linux-x86_64
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine artifacts
        run: |
          mkdir -p combined-release
          find artifacts -type f -exec cp {} combined-release/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: combined-release/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
