name: Release Builds

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install macOS build dependencies
        if: runner.os == 'macOS'
        run: |
          brew install libtiff libjpeg webp little-cms2 openssl@1.1 2>/dev/null || true
          export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
          export CPPFLAGS="-I$(brew --prefix openssl@1.1)/include"

      - name: Build macOS universal binary
        if: runner.os == 'macOS'
        run: |
          # Create separate build environments
          python -m venv arm64_env
          source arm64_env/bin/activate
          pip install numpy pillow pyinstaller -r requirements.txt
          python -m PyInstaller \
            --onefile \
            --name=RSPA \
            --target-arch arm64 \
            --distpath arm64_dist \
            --workpath arm64_build \
            main.py
          deactivate
          
          python -m venv x86_env
          source x86_env/bin/activate
          arch -x86_64 pip install numpy pillow pyinstaller -r requirements.txt
          arch -x86_64 python -m PyInstaller \
            --onefile \
            --name=RSPA \
            --target-arch x86_64 \
            --distpath x86_dist \
            --workpath x86_build \
            main.py
          deactivate
          
          # Create versioned release directory
          mkdir -p release/v${{ steps.version.outputs.version }}
          
          # Create universal binary using lipo
          lipo -create \
            -output release/v${{ steps.version.outputs.version }}/RSPA-${{ steps.version.outputs.version }}-macos-universal \
            arm64_dist/RSPA \
            x86_dist/RSPA
          
          # Create architecture-specific copies
          cp arm64_dist/RSPA release/v${{ steps.version.outputs.version }}/RSPA-${{ steps.version.outputs.version }}-macos-arm64
          cp x86_dist/RSPA release/v${{ steps.version.outputs.version }}/RSPA-${{ steps.version.outputs.version }}-macos-x86_64
          
          # Make executable
          chmod +x release/v${{ steps.version.outputs.version }}/RSPA-${{ steps.version.outputs.version }}-macos-*

      - name: Build Windows executable
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt
          pyinstaller --onefile --name=RSPA main.py
          mkdir -p release/v${{ steps.version.outputs.version }}
          Move-Item dist/RSPA.exe release/v${{ steps.version.outputs.version }}/RSPA-${{ steps.version.outputs.version }}-windows-x86_64.exe

      - name: Build Linux executable
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt
          pyinstaller --onefile --name=RSPA main.py
          mkdir -p release/v${{ steps.version.outputs.version }}
          mv dist/RSPA release/v${{ steps.version.outputs.version }}/RSPA-${{ steps.version.outputs.version }}-linux-x86_64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine artifacts
        run: |
          # Create versioned release directory
          mkdir -p release/v${{ needs.build.outputs.version }}
          
          # Find and copy all versioned assets
          find artifacts -name "RSPA-*" -exec cp {} release/v${{ needs.build.outputs.version }}/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          files: release/v${{ needs.build.outputs.version }}/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
