name: Release Builds

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install macOS build dependencies
        if: matrix.os == 'macOS-latest'
        run: |
          # Install Homebrew if not present
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "$(brew --prefix)/opt" >> $GITHUB_PATH
          
          # Install required libraries
          brew install libtiff libjpeg webp little-cms2 openssl@1.1
          export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
          export CPPFLAGS="-I$(brew --prefix openssl@1.1)/include"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            # Force universal2 builds for key packages
            export ARCHFLAGS="-arch arm64 -arch x86_64"
            pip install numpy --no-binary numpy --force-reinstall
            pip install pillow --no-binary pillow --force-reinstall
          fi
          pip install pyinstaller -r requirements.txt

      - name: Build executable
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            # Verify numpy is universal
            file $(python -c "import numpy._core._multiarray_umath; print(numpy._core._multiarray_umath.__file__)")
            
            # Build universal binary
            python -m PyInstaller \
              --onefile \
              --name=rifle_spread_analysis \
              --target-arch universal2 \
              --workpath build_macos \
              --distpath dist_macos \
              main.py
            
            mkdir -p release
            cp dist_macos/rifle_spread_analysis release/rifle_spread_analysis-macos-universal
            cp dist_macos/rifle_spread_analysis release/rifle_spread_analysis-macos-arm64
            cp dist_macos/rifle_spread_analysis release/rifle_spread_analysis-macos-x86_64
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --onefile --name=rifle_spread_analysis main.py
            mkdir -p release
            mv dist/rifle_spread_analysis.exe release/rifle_spread_analysis-windows-x86_64.exe
          else
            pyinstaller --onefile --name=rifle_spread_analysis main.py
            mkdir -p release
            mv dist/rifle_spread_analysis release/rifle_spread_analysis-linux-x86_64
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.os }}
          path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Combine artifacts
        run: |
          mkdir -p combined-release
          find artifacts -name "rifle_spread_analysis*" -exec cp {} combined-release/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: combined-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
